pipeline {
  agent any 
  stages{
    stage ('checkout') {
      steps{
checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/bharah08/terraform-zero-to-hero.git']])
      }
    }
    stage ('terraform-int') {
      steps{
sh 'terraform init Day-3/'
      }
    }
     stage ('terraform-plan') {
      steps{
sh 'terraform plan Day-3/'
      }
    }
     stage ('terraform-apply') {
      steps{
sh 'terraform apply  --auto-approve Day-3/'
      }
    }
  }
}
